# Base settings for debian/APT, configure sudo and NTP
#
#
# Copyright (C) 2013 Calogero Lo Leggio <kalos@nerdrug.org>
#
# This part of software is released under the terms of the GPLv3 license.
#

- name: Create home directories
  become: no
  file: path=/home/{{user}}/{{item}} state=directory mode=0755
  with_items:
    - dev
    - bin

- name: Build tools
  apt: name={{item}} state=installed
  items:
    - libtool
    -  libtool-bin
    -  autoconf
    -  automake
    -  cmake
    -  g++
    -  pkg-config
    -  unzip


- name: Install ectkeeper
  apt: name=etckeeper state=installed
  register: etckeeper_installed

# FIXME: the git repo does not exist stright away
#
# - name: Turn off git pgpsign for etckeeper
#   sudo: true
#   command: git config --local commit.pgpsign false
#   args:
#     chdir: /etc
#   when: etckeeper_installed.changed

# { NTP


- name: Install NTP deamon
  apt: name=ntp state=installed

- name: Install ntpdate
  apt: name=ntpdate state=installed

- name: NTP should be running
  service: name=ntp state=running enabled=yes

# FIXME: this fails, locally and on VM
# - name: exec ntpdate
#   command: ntpdate-debian
#
#- name: Sync time
  #command: ntpdate pool.ntp.org
# }

# FIXME: this fails on Vagrant because we are connecting via
#         SSH and not within an XSession: Cannot open display \"default display\
#
# - name: Set US keyboard layout
#   command: setxkbmap us

- name: 'Add GB locale'
  locale_gen:
    name: en_GB.UTF-8
    state: present

- name: Set locale
  command: update-locale LANG=en_GB.UTF-8 LANGUAGE=en_GB

- name: Set locale
  lineinfile: dest=/etc/environment regexp="^LANG=" line="LANG=en_GB.UTF-8"

- name: Set locale
  lineinfile: dest=/etc/environment regexp="^LC_ALL=" line="LC_ALL=en_GB.UTF-8"
